### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/js/lib/socket.io.min.js' - v14

### ISSUE THREAD

**Issue by muchai** [frappe/chat#44] opened 2022-08-17 17:42 UTC
https://github.com/frappe/frappe/issues/17852

**Comment by blewsky** [comment] 2022-08-20 04:37
Same here on Frappe Cloud after migrating from a V13 backup.

**Comment by blewsky** [comment] 2022-08-20 04:39
Duplicate of https://github.com/frappe/chat/issues/43

**Closed** 2022-08-25 05:32 UTC
