### ISSUE TITLE
i get this issue with erpnext v-14-beta

### ISSUE THREAD

**Issue by Abdo2021-a** [frappe/chat#43] opened 2022-07-25 13:07 UTC
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/js/lib/socket.io.min.js'

**Comment by tradaonline** [comment] 2022-08-08 04:38
This error still occurs with the official 14 version

**Comment by Abdo2021-a** [comment] 2022-08-08 10:38
@tradaonline  if you face this problem with version 14 you can put the configration in the missed file 
take this config from defaut erp or another site erpnext u have

**Comment by ioscanner** [comment] 2022-08-24 16:00
Confirmed the patch #41 works and allows chat to work again.  But the issue is now that chat messages don't update.  So you don't see new messages received in chat sessions.  You have to reload to see them.  That makes chat not usable.

**Comment by surajshetty3416** [comment] 2022-08-25 05:22
Should be resolved with https://github.com/frappe/chat/pull/41

**Closed by surajshetty3416** 2022-08-25 05:22 UTC

**Comment by ioscanner** [comment] 2022-08-25 10:13
It seems using the patch #41 Allows Chat to work, but causes an issue with the socket so now messages don't show up for users.  They must reload to see the messages.  This was also the issue with #3 and have a video of the issue.  So seems it allows chat to start patch #41 causes a new issue.  Someone else said to just create the missing socket file "assets/frappe/js/lib/socket.io.min.js"  I might try that today and see if it resolves the issue and roll back the patch.

**Comment by hamzahabeeb** [comment] 2023-10-17 05:28
> It seems using the patch #41 Allows Chat to work, but causes an issue with the socket so now messages don't show up for users. They must reload to see the messages. This was also the issue with #3 and have a video of the issue. So seems it allows chat to start patch #41 causes a new issue. Someone else said to just create the missing socket file "assets/frappe/js/lib/socket.io.min.js" I might try that today and see if it resolves the issue and roll back the patch.
> 
> Bump: @surajshetty3416

did it work?
